package com.cbsinc.cms.publisher.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity(name =  "account")
public class Account implements java.io.Serializable {
    

    /**
   * 
   */
  private static final long serialVersionUID = -5547983289905004721L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	private long accountId;
	
    @Column(name= "USER_ID")
    private Long userId;
    
    @Column(name="AMOUNT",precision = 22,scale = 0,nullable = false)
	private double amount;
    
    @Column(name="CURR")
	private Integer curr;
    
    @Column(name="DATA_INPUT",length=19,nullable=false)
    @Temporal(TemporalType.TIMESTAMP)
	private Date dateInput;
    
    @Column(name="DESCRIPTION",length=200)
	private String description;
    
    @Column(name="COMPLETE",nullable=false)
	private boolean complete;
    
    @Column(name="ACTIVE",nullable = false)
	private boolean active;
	
	@Column(name="CURRENCY_ID")
	private Long currencyId;
	
	@Column(name="TREE_ID")
	private Long treeId;

	public Account() {
	}

	public Account(long accountId, double amount, Date dateInput,
			boolean complete, boolean active) {
		this.accountId = accountId;
		this.amount = amount;
		this.dateInput = dateInput;
		this.complete = complete;
		this.active = active;
	}

	public Account(long accountId, Long userId, double amount, Integer curr,
			Date dateInput, String description, boolean complete,
			boolean active, Long currencyId, Long treeId) {
		this.accountId = accountId;
		this.userId = userId;
		this.amount = amount;
		this.curr = curr;
		this.dateInput = dateInput;
		this.description = description;
		this.complete = complete;
		this.active = active;
		this.currencyId = currencyId;
		this.treeId = treeId;
	}

	

}
