package com.cbsinc.cms.publisher.entity;

// Generated 29.03.2014 21:04:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.annotation.Nonnull;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * AccountHist generated by hbm2java
 */
@Entity(name="account_hist")
@Table(name = "account_hist")
public class AccountHist implements java.io.Serializable {

  public AccountHist() {
    super();
    // TODO Auto-generated constructor stub
  }

  private static final long serialVersionUID = -3190707429730685074L;

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  @Column(name = "USER_ID")
  private Long userId;

  @Column(name = "ADD_AMOUNT", precision = 22, scale = 0)
  private Double addAmount;

  @Column(name = "OLD_AMOUNT", precision = 22, scale = 0)
  private Double oldAmount;

  @Column(name = "NUM_DAY")
  private Integer numDay;

  @Column(name = "DATE_INPUT", length = 19, nullable = false)
  private Date dateInput;

  @Column(name = "COMPLETE")
  private boolean complete;

  @Column(name = "DECSRIPTION", length = 200)
  private String decsription;

  @Column(name = "ACTIVE", nullable = false)
  @Nonnull
  private boolean active;

  @Column(name = "REZULT_CD", length = 10)
  private String rezultCd;

  @Column(name = "DATE_END", length = 19)
  @Temporal(TemporalType.TIMESTAMP)
  private Date dateEnd;

  @Column(name = "SYSDATE", length = 19)
  @Temporal(TemporalType.TIMESTAMP)
  private Date sysdate;

  @Column(name = "TAX", precision = 22, scale = 0)
  private Double tax;

  @Column(name = "SOFT_ID")
  private Long softId;

  @Column(name = "RATE", precision = 22, scale = 0, nullable = false)
  @Nonnull
  private double rate;

  @Column(name = "CURRENCY_ID_ADD")
  private Integer currencyIdAdd;

  @Column(name = "CURRENCY_ID_OLD")
  private Integer currencyIdOld;

  @Column(name = "CURRENCY_ID_TOTAL")
  private Integer currencyIdTotal;

  @Column(name = "TOTAL_AMOUNT", precision = 22, scale = 0)
  private Double totalAmount;

  @Column(name = "WITHTAX_TOTAL_AMOUNT", precision = 22, scale = 0)
  private Double withtaxTotalAmount;

  @Column(name = "USER_IP", length = 15)
  private String userIp;
  @Column(name = "USER_HEADER", length = 500)
  private String userHeader;
  @Column(name = "USER_LOCALE", length = 2)
  private String userLocale;

  @Column(name = "USER_OS", length = 10)
  private String userOs;

  @Column(name = "USER_OS_PACK", length = 10)
  private String userOsPack;

  @Column(name = "ORDER_ID")
  private Long orderId;



  public AccountHist(long id, Date dateInput, boolean active, double rate) {
    this.id = id;
    this.dateInput = dateInput;
    this.active = active;
    this.rate = rate;
  }



}
