package com.cbsinc.cms.publisher.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Basket generated by hbm2java
 */

@Entity
@Table(name = "basket")
public class Basket implements java.io.Serializable {

	private static final long serialVersionUID = -8779247638594396273L;

	@Id
	@Column(name = "BASKET_ID")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long basketId;

	@Column(name = "PRODUCT_ID")
	private Long productId;

	@Column(name = "ORDER_ID")
	private Long orderId;

	@Column(name = "QUANTITY")
	private Integer quantity;

	public Basket(long basketId) {
		this.basketId = basketId;
	}

	public long getBasketId() {
		return basketId;
	}

	public void setBasketId(long basketId) {
		this.basketId = basketId;
	}

	public Long getProductId() {
		return productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Basket(long basketId, Long productId, Long orderId, Integer quantity) {
		super();
		this.basketId = basketId;
		this.productId = productId;
		this.orderId = orderId;
		this.quantity = quantity;
	}

	@Override
	public String toString() {
		return "Basket [basketId=" + basketId + ", productId=" + productId + ", orderId=" + orderId + ", quantity="
				+ quantity + "]";
	}

	
	
}
