SET GLOBAL sql_mode='NO_AUTO_VALUE_ON_ZERO';
CREATE TABLE IF NOT EXISTS ONE_SEQUENCES(ID INTEGER AUTO_INCREMENT  NOT NULL PRIMARY KEY);
CREATE   TABLE IF NOT EXISTS  ACCESSLEVEL(ACCESSLEVEL_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(250),DESCRIPTION VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE   TABLE IF NOT EXISTS  ACCOUNT(ACCOUNT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,USER_ID INTEGER,AMOUNT DOUBLE,CURR INTEGER,DATE_INPUT TIMESTAMP,DESCRIPTION VARCHAR(200),COMPLETE BOOLEAN DEFAULT true NOT NULL,ACTIVE BOOLEAN DEFAULT true NOT NULL,CURRENCY_ID INTEGER,TREE_ID INTEGER);
CREATE   TABLE IF NOT EXISTS  ACCOUNT_HIST(ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,USER_ID INTEGER,ADD_AMOUNT DOUBLE,OLD_AMOUNT DOUBLE,NUM_DAY INTEGER,DATE_INPUT TIMESTAMP,COMPLETE BOOLEAN,DECSRIPTION VARCHAR(200),ACTIVE BOOLEAN DEFAULT true NOT NULL,REZULT_CD VARCHAR(10),DATE_END TIMESTAMP,SYSDATE TIMESTAMP,TAX DOUBLE,SOFT_ID INTEGER,RATE DOUBLE,CURRENCY_ID_ADD INTEGER,CURRENCY_ID_OLD INTEGER,CURRENCY_ID_TOTAL INTEGER,TOTAL_AMOUNT DOUBLE,WITHTAX_TOTAL_AMOUNT DOUBLE,USER_IP VARCHAR(15),USER_HEADER VARCHAR(500),USER_LOCALE VARCHAR(2),USER_OS VARCHAR(10),USER_OS_PACK VARCHAR(10),ORDER_ID BIGINT);
CREATE   TABLE IF NOT EXISTS  BASKET(BASKET_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,PRODUCT_ID BIGINT,ORDER_ID BIGINT,QUANTITY INTEGER DEFAULT 1);
CREATE   TABLE IF NOT EXISTS  BIG_IMAGES(BIG_IMAGES_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,IMGNAME VARCHAR(1000),IMG_URL VARCHAR(200),USER_ID INTEGER);
CREATE   TABLE IF NOT EXISTS  CALENDAR(CALENDAR_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,SOFT_ID INTEGER,HOLDDATE INTEGER,FIST_NAME VARCHAR(250),LAST_NAME VARCHAR(250),FATHER_NAME VARCHAR(250),DOCUMENT_NUMBER VARCHAR(250),DOCUMENT_TYPE VARCHAR(250),AGE VARCHAR(250),ACTIVE BOOLEAN,NOTE VARCHAR(500),PARENT_ID INTEGER,NODE_NAME VARCHAR(500),SITE_ID INTEGER NOT NULL,BASKET_ID INTEGER);
CREATE   TABLE IF NOT EXISTS  CATALOG(ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,USER_ID INTEGER,LABLE VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL,TAX DOUBLE,DESCRIPTION VARCHAR(500),SITE_ID INTEGER,LANG_ID INTEGER,PARENT_ID INTEGER,CATALOG_IMAGE_ID INTEGER);
CREATE INDEX CATALOG_1 ON CATALOG(PARENT_ID,ACTIVE);
CREATE   TABLE IF NOT EXISTS  CATALOG_IMAGES(CATALOG_IMAGES_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,IMGNAME VARCHAR(500),IMG_URL VARCHAR(200),USER_ID INTEGER);
CREATE  TABLE IF NOT EXISTS  CRETERIA1(CRETERIA1_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA2(CRETERIA2_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA3(CRETERIA3_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA4(CRETERIA4_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA5(CRETERIA5_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(1000));
CREATE   TABLE IF NOT EXISTS  CRETERIA6(CRETERIA6_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA7(CRETERIA7_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA8(CRETERIA8_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA9(CRETERIA9_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CRETERIA10(CRETERIA10_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),ACTIVE BOOLEAN,LANG_ID INTEGER,LINK_ID INTEGER DEFAULT 0 NOT NULL,CATALOG_ID INTEGER DEFAULT 0 NOT NULL,LABEL VARCHAR(500));
CREATE   TABLE IF NOT EXISTS  CURRENCY_RATE(CURRENCY_RATE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY);
CREATE  TABLE IF NOT EXISTS  FILE(FILE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),FILEDATA BINARY,USER_ID INTEGER,SIZE VARCHAR(15),PATH VARCHAR(500));
CREATE  TABLE IF NOT EXISTS  IMAGES(IMAGE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,IMGNAME VARCHAR(500),IMG_URL VARCHAR(500),USER_ID INTEGER);
CREATE  TABLE IF NOT EXISTS  LANG(LANG_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,LABLE VARCHAR(250),DESCRIPTION VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE  TABLE IF NOT EXISTS  ORDERS_HIST(ORDER_HIST_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,ORDER_HIST_CD BIGINT,USER_ID INTEGER,POSITION_ID INTEGER,DELIVERY_TIMEEND TIMESTAMP,AMOUNT DOUBLE,TAX DOUBLE,END_AMOUNT DOUBLE,DELIVERY_AMOUNT DOUBLE,CARD_ID INTEGER,DELIVERY_LONG INTEGER,SHIPMENT_ADDRESS_ID INTEGER,SERIAL_NUMBER VARCHAR(250),PAYSTATUS_ID INTEGER,DELIVERYSTATUS_ID INTEGER DEFAULT 0)
CREATE  TABLE IF NOT EXISTS  PAY_GATEWAY(PAY_GATEWAY_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME_GATEWAY VARCHAR(250),FULLNAME_GATEWAY VARCHAR(500),PHONE VARCHAR(15),FAX VARCHAR(15),SITE_URL VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE  TABLE IF NOT EXISTS  PAYSTATUS(PAYSTATUS_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,LABLE VARCHAR(500),DESCRIPTION VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE  TABLE IF NOT EXISTS  PAYSYSTEM(PAYSYSTEM_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,PAYSYSTEM_CD VARCHAR(250),NAME VARCHAR(500),DESCRIPTION VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL,IMG_URL VARCHAR(500),PAY_GATEWAY_ID INTEGER);
CREATE  TABLE IF NOT EXISTS  PORTLETTYPE(PORTLETTYPE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(500),LANG_ID INTEGER);
CREATE  TABLE IF NOT EXISTS  SALELOGIC(SALELOGIC_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(250),Describtion VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE  TABLE IF NOT EXISTS  SHOP(SHOP_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,SHOP_CD INTEGER,OWNER_ID INTEGER,LOGIN VARCHAR(250),SITE_ID INTEGER,PAY_GATEWAY_ID INTEGER DEFAULT 0,PASSWD VARCHAR(250),CDATE TIMESTAMP)
CREATE  TABLE IF NOT EXISTS  SITE(SITE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,HOST VARCHAR(500),OWNER INTEGER,ACTIVE BOOLEAN DEFAULT true NOT NULL,HOME_DIR VARCHAR(500),SITE_DIR VARCHAR(500),PERSON VARCHAR(200),PHONE VARCHAR(500),ADDRESS VARCHAR(300),SUBJECT_SITE VARCHAR(300),NICK_SITE VARCHAR(200),COMPANY_NAME VARCHAR(500))
CREATE  TABLE IF NOT EXISTS  TREE(ITEM_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NODE_ID INTEGER,FOLDER_NAME VARCHAR(250),OWNER_ID INTEGER,GROUP_ID INTEGER,ACTIVE BOOLEAN DEFAULT true NOT NULL,DOC_ID INTEGER,CDATE TIMESTAMP,LAST_TOUCH_ID INTEGER,LAST_TIME TIMESTAMP)
CREATE  TABLE IF NOT EXISTS  TUSER(USER_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,LOGIN VARCHAR(250),PASSWD VARCHAR(500),FIRST_NAME VARCHAR(500),LAST_NAME VARCHAR(500),COMPANY VARCHAR(250),E_MAIL VARCHAR(250),PHONE VARCHAR(250),MOBIL_PHONE VARCHAR(250),FAX VARCHAR(250),ICQ VARCHAR(250),WEBSITE VARCHAR(500),QUESTION VARCHAR(200),ANSWER VARCHAR(200),IDSESSION VARCHAR(500),BIRTHDAY TIMESTAMP,REGDATE TIMESTAMP,LEVELUP_CD INTEGER,BANK_CD INTEGER,ACVIVE_SESSION BOOLEAN,ACTIVE BOOLEAN DEFAULT true NOT NULL,COUNTRY VARCHAR(20),CITY VARCHAR(20),ZIP VARCHAR(10),STATE VARCHAR(10),SCOUNTRY VARCHAR(250),MIDDLENAME VARCHAR(250),CITY_ID INTEGER,COUNTRY_ID INTEGER,CURRENCY_ID INTEGER,TREE_ID INTEGER,SITE_ID INTEGER DEFAULT 0 NOT NULL)
CREATE INDEX TUSER_INDEX1 ON TUSER(LOGIN,PASSWD,SITE_ID);
CREATE INDEX TUSER_INDEX2 ON TUSER(LOGIN,PASSWD);
CREATE  TABLE IF NOT EXISTS  TYPESOFT(TYPE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,USER_ID INTEGER,TYPE_LABLE VARCHAR(250),TYPE_DESC VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL,TAX DOUBLE DEFAULT 0.0E0 NOT NULL)
CREATE  TABLE IF NOT EXISTS  XSL_STYLE(XSL_STYLE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(250),DESCRIPTION VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL,PRODUCER_ID INTEGER DEFAULT 0 NOT NULL,OWNER_ID INTEGER DEFAULT 0 NOT NULL,COST DOUBLE DEFAULT 0.0E0 NOT NULL,CURRENCY_ID INTEGER DEFAULT 0 NOT NULL,SYS_DATE TIMESTAMP,SITE_ID INTEGER DEFAULT 0 NOT NULL,DIRNAME VARCHAR(200),XSL_SUBJ_ID INTEGER)
CREATE  TABLE IF NOT EXISTS  XSL_SUBJ(XSL_SUBJ_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(250),DESCRIPTION VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL)
CREATE  TABLE IF NOT EXISTS  ORDERS(ORDER_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,USER_ID INTEGER,DELIVERY_TIMEEND TIMESTAMP,AMOUNT DOUBLE,TAX DOUBLE,END_AMOUNT DOUBLE,DELIVERY_AMOUNT DOUBLE,DELIVERY_LONG INTEGER,PAYSTATUS_ID INTEGER,DELIVERY_START TIMESTAMP,CDATE TIMESTAMP,CURRENCY_ID INTEGER,COUNTRY_ID INTEGER,CITY_ID INTEGER,ADDRESS VARCHAR(200),PHONE VARCHAR(250),CONTACT_PERSON VARCHAR(200),EMAIL VARCHAR(500),FAX VARCHAR(250),DESCRIPTION VARCHAR(1000),ZIP INTEGER,TREE_ID INTEGER,IMEI INTEGER,PHONEMODEL_ID INTEGER DEFAULT 0,DELIVERYSTATUS_ID INTEGER DEFAULT 0)
CREATE  TABLE IF NOT EXISTS  SOFT(SOFT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(10000),DESCRIPTION VARCHAR(1000000),VERSION VARCHAR(10),COST DOUBLE DEFAULT 0.0E0 NOT NULL,CURRENCY INTEGER DEFAULT 0 NOT NULL,SERIAL_NUBMER VARCHAR(250),FILE_ID INTEGER,TYPE_ID INTEGER,LEVELUP INTEGER,ACTIVE BOOLEAN DEFAULT true NOT NULL,USER_ID INTEGER,PHONETYPE_ID INTEGER,PROGNAME_ID INTEGER,IMAGE_ID INTEGER,BIGIMAGE_ID INTEGER,WEIGHT DOUBLE,"COUNT" INTEGER,LANG_ID INTEGER,PHONEMODEL_ID INTEGER,LICENCE_ID INTEGER,CATALOG_ID INTEGER DEFAULT 1,SALELOGIC_ID INTEGER,TREE_ID INTEGER,CARD_NUMBER INTEGER,CARD_CODE INTEGER,START_DIAL_TIME TIMESTAMP,END_DIAL_TIME TIMESTAMP,START_ACTIVATION_CARD BOOLEAN DEFAULT false NOT NULL,END_ACTIVATION_CARD BOOLEAN DEFAULT false NOT NULL,TYPE_CARD_ID INTEGER DEFAULT 0,PRODUCT_CODE INTEGER,FULLDESCRIPTION CLOB,SITE_ID INTEGER,SEARCH VARCHAR(100),PORTLETTYPE_ID INTEGER DEFAULT 0 NOT NULL,CRETERIA1_ID INTEGER,CRETERIA2_ID INTEGER,CRETERIA3_ID INTEGER,CRETERIA4_ID INTEGER,CRETERIA5_ID INTEGER,CRETERIA6_ID INTEGER,CRETERIA7_ID INTEGER,CRETERIA8_ID INTEGER,CRETERIA9_ID INTEGER,CRETERIA10_ID INTEGER,STATISTIC_ID INTEGER DEFAULT 0,CDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CRETERIA11_ID INTEGER DEFAULT 0,CRETERIA12_ID INTEGER DEFAULT 0,CRETERIA13_ID INTEGER DEFAULT 0,CRETERIA14_ID INTEGER DEFAULT 0,CRETERIA15_ID INTEGER DEFAULT 0,SQUARE INTEGER DEFAULT 0,RATING_SUMM1 INTEGER DEFAULT 0,RATING_SUMM2 INTEGER DEFAULT 0,RATING_SUMM3 INTEGER DEFAULT 0,COUNTPOST_RATING1 INTEGER DEFAULT 0,COUNTPOST_RATING2 INTEGER DEFAULT 0,COUNTPOST_RATING3 INTEGER DEFAULT 0,MIDLE_BAL1 INTEGER DEFAULT 0,MIDLE_BAL2 INTEGER DEFAULT 0,MIDLE_BAL3 INTEGER DEFAULT 0,SHOW_RATING1 BOOLEAN DEFAULT false NOT NULL,SHOW_RATING2 BOOLEAN DEFAULT false NOT NULL,SHOW_RATING3 BOOLEAN DEFAULT false NOT NULL,SHOW_BLOG BOOLEAN DEFAULT false NOT NULL,NAME2 VARCHAR(250),SEARCH2 VARCHAR(100),AMOUNT1 DOUBLE DEFAULT 0.0E0,AMOUNT2 DOUBLE DEFAULT 0.0E0,AMOUNT3 DOUBLE DEFAULT 0.0E0,JSP_URL VARCHAR(500),COLOR VARCHAR(10));
CREATE INDEX NAVIGATOR_PRODUCT_INDEX1 ON SOFT(CATALOG_ID,PORTLETTYPE_ID,ACTIVE);
CREATE INDEX INDEX_CATALOG ON SOFT(CATALOG_ID);
CREATE INDEX NAVIGATOR_PRODUCT_INDEX3 ON SOFT(IMAGE_ID,BIGIMAGE_ID,FILE_ID,CRETERIA1_ID,CRETERIA2_ID,CRETERIA3_ID,CRETERIA4_ID,CRETERIA5_ID,CRETERIA6_ID,CRETERIA7_ID,CRETERIA8_ID,CRETERIA9_ID,CRETERIA10_ID);
CREATE INDEX NAVIGATOR_PRODUCT_INDEX4 ON SOFT(CATALOG_ID,PORTLETTYPE_ID,ACTIVE);
CREATE INDEX NAVIGATOR_PRODUCT_INDEX5 ON SOFT(PORTLETTYPE_ID,ACTIVE,SITE_ID);
CREATE  TABLE IF NOT EXISTS  CURRENCY(CURRENCY_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,RATE DOUBLE,CURRENCY_LABLE VARCHAR(1000),CURRENCY_DESC VARCHAR(500),ACTIVE BOOLEAN,CURRENCY_CD VARCHAR(500),CURSDATE VARCHAR(500),CHANGEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE  TABLE IF NOT EXISTS  LICENCE(LICENCE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,LABLE VARCHAR(250),DESCRIPTION VARCHAR(1000),ACTIVE BOOLEAN DEFAULT true NOT NULL,SITE_ID INTEGER,LANG_ID INTEGER);
CREATE  TABLE IF NOT EXISTS  DINAMIC_FIELDS(DINAMIC_FIELD_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,PRODUCT_ID BIGINT,ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE  TABLE IF NOT EXISTS  DELIVERYSTATUS(DELIVERYSTATUS_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,LABLE VARCHAR(250),DESCRIPTION VARCHAR(500),ACTIVE BOOLEAN DEFAULT true NOT NULL,LANG VARCHAR(2) DEFAULT 'ru');
CREATE  TABLE IF NOT EXISTS  CITY(CITY_ID INTEGER,TELCODE INTEGER,NAME VARCHAR(250),FULLNAME VARCHAR(500),COUNTRY_ID INTEGER,LANG_ID INTEGER,LOCALE VARCHAR(2));
CREATE  TABLE IF NOT EXISTS  COUNTRY(COUNTRY_ID INTEGER,TELCODE INTEGER,NAME VARCHAR(250),FULLNAME VARCHAR(500),LANG_ID INTEGER,LOCALE VARCHAR(2));
CREATE  TABLE IF NOT EXISTS  SERVICE_STATUS_EVENTS(SITE_ID INTEGER,DATE_SEND TIMESTAMP,CLASSBODY OBJECT,SERVICE_STATUS INTEGER,ISNOTIFY BOOLEAN DEFAULT false NOT NULL,ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE  TABLE IF NOT EXISTS  SERVICE_STATUS_EVENTS_HISTORY(SITE_ID INTEGER,DATE_SEND TIMESTAMP,SERVICE_STATUS INTEGER,CLASSBODY OBJECT,ISNOTIFY BOOLEAN DEFAULT false NOT NULL,ACTIVE BOOLEAN DEFAULT true NOT NULL);
CREATE  TABLE IF NOT EXISTS  DOMAIN_PROC(DOMAIN_PROC_ID INTEGER DEFAULT 0 NOT NULL,LAST_DATE TIMESTAMP)	;
CREATE  TABLE IF NOT EXISTS  STORE_SESSION(IDSESSION_HASH1 BIGINT,IDSESSION_HASH2 BIGINT,IDSESSION_HASH3 BIGINT,IDSESSION_HASH4 BIGINT,USER_ID INTEGER,TYPE VARCHAR(200),LASTURL VARCHAR(500),CLASSBODY VARCHAR(500),BCLASSBODY BLOB,ACTIVE BOOLEAN DEFAULT true NOT NULL,CDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
ALTER TABLE IF NOT EXISTS  ONE_SEQUENCES ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE IF NOT EXISTS  ACCESSLEVEL ALTER COLUMN ACCESSLEVEL_ID RESTART WITH 0; 
ALTER TABLE IF NOT EXISTS  ACCOUNT ALTER COLUMN ACCOUNT_ID RESTART WITH 2512;
ALTER TABLE IF NOT EXISTS  ACCOUNT_HIST ALTER COLUMN ID RESTART WITH 6549;
ALTER TABLE IF NOT EXISTS  BASKET ALTER COLUMN BASKET_ID RESTART WITH 438;
ALTER TABLE IF NOT EXISTS  BIG_IMAGES ALTER COLUMN BIG_IMAGES_ID RESTART WITH 505;
ALTER TABLE IF NOT EXISTS  CALENDAR ALTER COLUMN CALENDAR_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  CATALOG ALTER COLUMN ID RESTART WITH 9554;
ALTER TABLE IF NOT EXISTS  CATALOG_IMAGES ALTER COLUMN CATALOG_IMAGES_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  CRETERIA1 ALTER COLUMN CRETERIA1_ID RESTART WITH 1371;
ALTER TABLE IF NOT EXISTS  CRETERIA2 ALTER COLUMN CRETERIA2_ID RESTART WITH 694;
ALTER TABLE IF NOT EXISTS  CRETERIA3 ALTER COLUMN CRETERIA3_ID RESTART WITH 1533;
ALTER TABLE IF NOT EXISTS  CRETERIA4 ALTER COLUMN CRETERIA4_ID RESTART WITH 163;
ALTER TABLE IF NOT EXISTS  CRETERIA5 ALTER COLUMN CRETERIA5_ID RESTART WITH 212;
ALTER TABLE IF NOT EXISTS  CRETERIA6 ALTER COLUMN CRETERIA6_ID RESTART WITH 79;;
ALTER TABLE IF NOT EXISTS  CRETERIA7 ALTER COLUMN CRETERIA7_ID RESTART WITH 212;
ALTER TABLE IF NOT EXISTS  CRETERIA8 ALTER COLUMN CRETERIA8_ID RESTART WITH 92;
ALTER TABLE IF NOT EXISTS  CRETERIA9 ALTER COLUMN CRETERIA9_ID RESTART WITH 212;
ALTER TABLE IF NOT EXISTS  CRETERIA10 ALTER COLUMN CRETERIA10_ID RESTART WITH 79;
ALTER TABLE IF NOT EXISTS  CURRENCY_RATE ALTER COLUMN CURRENCY_RATE_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  FILE ALTER COLUMN FILE_ID RESTART WITH 592;
ALTER TABLE IF NOT EXISTS  IMAGES ALTER COLUMN IMAGE_ID RESTART WITH 748;
ALTER TABLE IF NOT EXISTS  LANG ALTER COLUMN LANG_ID RESTART WITH 9;
ALTER TABLE IF NOT EXISTS  ORDERS_HIST ALTER COLUMN ORDER_HIST_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  PAY_GATEWAY ALTER COLUMN PAY_GATEWAY_ID RESTART WITH 2;
ALTER TABLE IF NOT EXISTS  PAYSTATUS ALTER COLUMN PAYSTATUS_ID RESTART WITH 4;
ALTER TABLE IF NOT EXISTS  PAYSYSTEM ALTER COLUMN PAYSYSTEM_ID RESTART WITH 11;
ALTER TABLE IF NOT EXISTS  PORTLETTYPE ALTER COLUMN PORTLETTYPE_ID RESTART WITH 3;
ALTER TABLE IF NOT EXISTS  SALELOGIC ALTER COLUMN SALELOGIC_ID RESTART WITH 32;
ALTER TABLE IF NOT EXISTS  SHOP ALTER COLUMN SHOP_ID RESTART WITH 682;
ALTER TABLE IF NOT EXISTS  SITE ALTER COLUMN SITE_ID RESTART WITH 793;
ALTER TABLE IF NOT EXISTS  TREE ALTER COLUMN ITEM_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  TUSER ALTER COLUMN USER_ID RESTART WITH 2529;
ALTER TABLE IF NOT EXISTS  TYPESOFT ALTER COLUMN TYPE_ID RESTART WITH 4;
ALTER TABLE IF NOT EXISTS  XSL_STYLE ALTER COLUMN XSL_STYLE_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  XSL_SUBJ ALTER COLUMN XSL_SUBJ_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  ORDERS ALTER COLUMN ORDER_ID RESTART WITH 302;
ALTER TABLE IF NOT EXISTS  SOFT ALTER COLUMN SOFT_ID RESTART WITH 17252;
ALTER TABLE IF NOT EXISTS  CURRENCY ALTER COLUMN CURRENCY_ID RESTART WITH 4;
ALTER TABLE IF NOT EXISTS  LICENCE ALTER COLUMN LICENCE_ID RESTART WITH 6;
ALTER TABLE IF NOT EXISTS  DINAMIC_FIELDS ALTER COLUMN DINAMIC_FIELD_ID RESTART WITH 0;
ALTER TABLE IF NOT EXISTS  DELIVERYSTATUS ALTER COLUMN DELIVERYSTATUS_ID RESTART WITH 7;
SET WRITE_DELAY 20
SET SCHEMA PUBLIC